export const DRINKS_REQUEST = 'DRINKS_REQUEST';
export const DRINKS_SINGLE_RECORD_REQUEST = 'DRINKS_SINGLE_RECORD_REQUEST';
export const DRINKS_SUCCESS = 'DRINKS_SUCCESS';
export const DRINKS_SINGLE_SUCCESS = 'DRINKS_SINGLE_SUCCESS';
export const DRINKS_ERROR = 'DRINKS_ERROR';
export const DRINKS_SORT_CHANGE = 'DRINKS_SORT_CHANGE';
export const DRINKS_LIMIT_CHANGE = 'DRINKS_LIMIT_CHANGE';
export const DRINKS_MAX = 'DRINKS_MAX';