export const PLACES_REQUEST = 'PLACES_REQUEST';
export const PLACES_INSERT_RECORD = 'PLACES_INSERT_RECORD';
export const PLACES_SUCCESS = 'PLACES_SUCCESS';
export const PLACES_CREATE_SUCCESS = 'PLACES_CREATE_SUCCESS';
export const PLACES_ERROR = 'PLACES_ERROR';
export const PLACES_SORT_CHANGE = 'PLACES_SORT_CHANGE';
export const PLACES_LIMIT_CHANGE = 'PLACES_LIMIT_CHANGE';
export const PLACES_MAX = 'PLACES_MAX';
export const PLACES_EDIT_SUCCESS = 'PLACES_EDIT_SUCCESS';

